baseurl = "https://yuji.im/en/"
languageCode = "en-us"
title = "Connecting the Dots"
author = "Yuji Shen"
# Shown in the side menu
copyright = "&copy; 2016"
canonifyurls = true
#RelativeURLs = true
paginate = 7
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Connecting the Dots"
  author = "Yuji Shen"
  brand = ""
  googleAnalytics = "UA-59613226-1"
  disqus = "yujishen"
  # CSS name for highlight.js
  # highlightjs = "solarizedlight"
  dateFormat = "01/2/2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='icon-home'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='icon-box'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='icon-folder'></i>"
    weight = 2
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='icon-tags'></i>"
    weight = 3
    identifier = "tag"
    url = "/tags/"

[intro]
  # Shown in the side menu.
  [[menu.intro]]
    name = "About"
    pre = "<i class='icon-user'></i>"
    weight = 0
    url = "/about/"
  [[menu.intro]]
    name = "Portfolio"
    pre = "<i class='icon-suitcase'></i>"
    weight = 1
    url = "/portfolio/"
  [[menu.intro]]
    name = "Resume"
    pre = "<i class='icon-file'></i>"
    weight = 2
    url = "/resume/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  # twitter = "*"
  # facebook = "*"
  # googleplus = "*"
  # weibo = "*"

  # SNS photo/video sharing
  # instagram = "*"
  # flickr = "*"
  # pinterest = "*"
  # youtube = "*"
  # vimeo = "*"
  # vine = "*"
  # slideshare = "*"

  # SNS career oriented
  linkedin = "yujishen"
  # xing = "*"

  # SNS news
  # reddit = "*"
  # hackernews = "*"

  # Techie
  github = "yujishen"
  # bitbucket = "*"
  # stackoverflow = "*"